import type { Garment } from "./garment-types";

/**
 * The canonical list of review kinds. This is the single source of
 * truth: the `Kind` type, the zod enum in lib/schema.ts, the nav, the
 * sitemap, llms.txt, the homepage tiles, the admin form and the tests
 * all derive from this array. Order is display order (it drives the
 * homepage tile sequence and the admin section list).
 *
 * A kind's key IS its content directory (`content/<kind>/`) and its
 * route (`/<kind>`), so adding one here means adding
 * `app/<kind>/page.tsx` + `app/<kind>/[slug]/page.tsx`. The drift
 * guard in tests/data-integrity.test.ts fails if you forget.
 */
export const KINDS = [
  "skincare",
  "supplements",
  "oral-care",
  "hair-care",
  "body-care",
  "essentials",
  "miscellaneous",
  "fashion",
] as const;

export type Kind = (typeof KINDS)[number];

/** Display label for each kind. Sentence case, matches the nav. */
export const KIND_LABEL: Record<Kind, string> = {
  skincare: "Skincare",
  supplements: "Supplements",
  "oral-care": "Oral care",
  "hair-care": "Hair care",
  "body-care": "Body care",
  essentials: "Essentials",
  miscellaneous: "Miscellaneous",
  fashion: "Fashion",
};

/** Listing route for a kind. Detail pages are `${kindPath(k)}/${slug}`. */
export function kindPath(kind: Kind): string {
  return `/${kind}`;
}

/** Runtime narrowing for untrusted strings (route params, form input). */
export function isKind(value: unknown): value is Kind {
  return (
    typeof value === "string" && (KINDS as readonly string[]).includes(value)
  );
}

export interface BuyLink {
  retailer: string;
  url: string;
}

/**
 * Per-region price object. Each field holds the locally-priced string
 * with its native currency symbol intact, e.g. `{ in: "₹2,400", us:
 * "$34", uk: "£28" }`. Honest about which markets we have data for:
 * missing entries simply don't render.
 */
export interface RegionalPrice {
  in?: string;
  us?: string;
  uk?: string;
}

export interface Review {
  kind: Kind;
  slug: string;
  name: string;
  brand: string;
  category: string;
  verdict?: "recommend" | "okay" | "bad";
  ratings?: {
    effect?: number;
    value?: number;
    tolerance?: number;
  };
  hidden?: boolean;
  retired?: boolean;
  retiredReason?: string;
  price?: string | RegionalPrice;
  servingsPerContainer?: number;
  dailyServings?: number;
  skinType?: string[];
  goal?: string[];
  routineNote?: string;
  routines: ("morning" | "evening" | "stack" | "shower" | "oral")[];
  crossList: Kind[];
  photo?: string;
  /**
   * Cold-mirror URL for the primary photo. When `photo` is a local
   * /products/... path served from Vercel static, this points at the
   * same file mirrored to Cloudflare R2. The detail-page gallery's
   * onError handler swaps to this if the local /public/ ever fails.
   * Generated by /tmp/dslr-scan/mirror-public-to-r2.py.
   */
  photoFallback?: string;
  photos: string[];
  video?: string;
  photoTimeline: { date: string; src: string; note?: string }[];
  boughtFromUrl?: string;
  indiaLinks: BuyLink[];
  westernLinks: BuyLink[];
  ukLinks: BuyLink[];
  ingredients?: string[];
  uvFilters?: string[];
  /** Fashion-only. Undefined on every other kind. */
  garment?: Garment;
  pros: string[];
  cons: string[];
  repurchase?: boolean;
  datePublished: string;
  lastUpdated?: string;
  changelog: { date: string; note: string }[];
  summary: string;
  body: string;
}

export interface ReviewSummary extends Omit<Review, "body"> {}

export interface Photo {
  src: string;
  alt: string;
  caption: string;
  location?: string;
  date: string;
  width: number;
  height: number;
  /**
   * Hide from the public `/photos` page without removing the entry
   * (or its Blob asset). Admin-only field; absent or false = visible.
   */
  hidden?: boolean;
  /**
   * Pin this frame as the hero (top of `/photos`). At most one entry
   * should set this. If none do, the newest-by-date photo becomes the
   * hero by default.
   */
  hero?: boolean;
  /**
   * Promote this frame to a full-bleed oversize moment inline within
   * its section, breaking out of the pair / offset rhythm. Any number
   * of photos can be featured; each becomes its own cinematic break
   * in the scroll.
   */
  featured?: boolean;
  /**
   * Pointer to the raw negative (CR3) on the One Touch archive drive.
   * Used as a record so that when an unedited camera-JPG frame earns
   * a permanent slot, the matching raw can be re-developed properly
   * in Lightroom and the higher-quality re-export takes its place at
   * the same Blob path. Empty/undefined means no raw is available
   * (e.g. the Joshua Tree session was JPG-only).
   */
  rawSource?: string;
  /**
   * Cold-mirror URL. If the primary `src` host ever breaks (Vercel Blob
   * egress cliff, Cloudflare R2 outage, etc.), `srcFallback` points at
   * a copy of the same file on a secondary host. Currently every R2
   * photo carries a GitHub Release URL here as the passive backup so
   * we always have two independently-served copies of every photo.
   */
  srcFallback?: string;
  /**
   * Tiny base64-encoded JPEG (typically 24×N px, ~500 bytes) used as
   * Next/Image's blurDataURL. Browser paints the blurred preview the
   * instant the HTML hits the DOM; the real image fades over it.
   * Generated by /tmp/dslr-scan/generate-lqip.py on every photo update.
   */
  blurDataURL?: string;
  /**
   * Larger inline AVIF (~20-30 KB base64) used ONLY on the hero photo
   * for instant-paint zero-network rendering. Regenerated by
   * /tmp/dslr-scan/build-hero-avif.py whenever the hero changes.
   */
  inlineAvif?: string;
  inlineAvifWidth?: number;
  inlineAvifHeight?: number;
  /**
   * Editorial tier:
   *   - "editorial" (default): part of the curated chapter layout
   *     (hero / anchor / featured / diptych / side caption rhythm).
   *   - "archive": unedited bulk imports that live in the dense
   *     contact-sheet grid after the editorial chapters, so they're
   *     browsable without diluting the curated experience.
   * Absent or "editorial" both treated as editorial.
   */
  tier?: "editorial" | "archive";
  /**
   * Optional EXIF / capture metadata. Rendered inline below the
   * caption when any field is present, so a photo can quietly tell
   * you what shot it. Empty fields are skipped, partial EXIF is
   * fine, missing EXIF is fine.
   */
  camera?: string;
  lens?: string;
  focalLength?: string; // "35mm", "85mm"
  aperture?: string; // "f/1.8"
  iso?: string | number;
  shutter?: string; // "1/250"
}

export type PrimerKind = "stack" | "ingredient";
export type PrimerDomain = "supplement" | "skincare" | "oral" | "meta";

export interface Primer {
  slug: string;
  title: string;
  subtitle?: string;
  kind: PrimerKind;
  domain: PrimerDomain;
  tags: string[];
  stack: string[];
  relatedProductSlugs: string[];
  datePublished: string;
  lastUpdated?: string;
  body: string;
}

export interface PrimerSummary extends Omit<Primer, "body"> {}
